/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseconn;

/**
 *
 * @author c3
 */
public class AccountCreation extends javax.swing.JFrame {
javax.swing.JFrame previous;
    /**
     * Creates new form AccountCreation
     */
    public AccountCreation(javax.swing.JFrame temp) {
        initComponents();
        previous=temp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABE1 = new javax.swing.JLabel();
        LABE2 = new javax.swing.JLabel();
        LABE3 = new javax.swing.JLabel();
        createAccount = new javax.swing.JButton();
        close = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LABE1.setFont(LABE1.getFont().deriveFont((LABE1.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        LABE1.setText("PHONE NUMBER ");
        getContentPane().add(LABE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 160, 30));

        LABE2.setFont(LABE2.getFont().deriveFont((LABE2.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        LABE2.setText("NAME");
        getContentPane().add(LABE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 80, 30));

        LABE3.setFont(LABE3.getFont().deriveFont((LABE3.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        LABE3.setText("ADDRESS");
        getContentPane().add(LABE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 80, 30));

        createAccount.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        createAccount.setText("CREATE ACCOUNT");
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });
        getContentPane().add(createAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 210, 30));

        close.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 210, 30));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 290, 40));
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 290, 40));
        getContentPane().add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 290, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed

        String n = name.getText();
        Bank.addAccount(n);
        DBI object = new DBI(this);
        object.setVisible(true);
        setVisible(false);
        
        
    }//GEN-LAST:event_createAccountActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABE1;
    private javax.swing.JLabel LABE2;
    private javax.swing.JLabel LABE3;
    private javax.swing.JTextField address;
    private javax.swing.JButton close;
    private javax.swing.JButton createAccount;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phno;
    // End of variables declaration//GEN-END:variables
}
