/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package databaseconn;

import java.awt.HeadlessException;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author c3
 */
public class DBI extends javax.swing.JFrame {
javax.swing.JFrame previous;
Statement stmt;
 ArrayList <BankAccount> tem;
    /**
     * Creates new form DBI
     * @param temp
     */
    public DBI(javax.swing.JFrame temp,Statement stmt) {
        initComponents();
        previous=temp;
        this.stmt=stmt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        details = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        depositFund = new javax.swing.JButton();
        accNumber = new javax.swing.JTextField();
        withdraw = new javax.swing.JButton();
        balance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LABE1 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        LABE2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Development Bank Of India ");
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel1ComponentHidden(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 650, 130));

        logOut.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        logOut.setText("Logout");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 210, 30));

        jLabel2.setFont(jLabel2.getFont().deriveFont((jLabel2.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        jLabel2.setText("Available Balance ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 210, 40));

        details.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        details.setText("Get Account Details ");
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        getContentPane().add(details, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 210, 30));

        jLabel3.setFont(jLabel3.getFont().deriveFont((jLabel3.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        jLabel3.setText("Enter Amount ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 210, 40));

        depositFund.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        depositFund.setText("Deposite Funds");
        depositFund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositFundActionPerformed(evt);
            }
        });
        getContentPane().add(depositFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 210, 30));
        getContentPane().add(accNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 290, 40));

        withdraw.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        withdraw.setText("Withdraw ");
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        getContentPane().add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 210, 30));

        balance.setFont(balance.getFont().deriveFont((balance.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 210, 40));

        jLabel6.setFont(jLabel6.getFont().deriveFont((jLabel6.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        jLabel6.setText("Account Number :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 210, 40));

        LABE1.setFont(LABE1.getFont().deriveFont((LABE1.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        getContentPane().add(LABE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 210, 30));
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 290, 40));

        LABE2.setFont(LABE2.getFont().deriveFont((LABE2.getFont().getStyle() | java.awt.Font.ITALIC), 18));
        LABE2.setText("Name  :  ");
        getContentPane().add(LABE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel1ComponentHidden

    }//GEN-LAST:event_jLabel1ComponentHidden

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logOutActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
        boolean attempt=true;
        String tempAc=accNumber.getText();
        while(attempt)
        {
            if(tempAc.equals(""))
            {
                JOptionPane.showMessageDialog(this,"account number cannot be empty");
                
            }
            else
            {
                break;
            }
            
        }
        int iterator=0;    
        tem=Bank.acc;
        while(true)
        {
            if(tem.get(iterator++).getAccountNumber()==Integer.parseInt(tempAc))
                break;
        }
        balance.setText((tem.get(iterator).getBalance()+""));
        LABE1.setText(tem.get(iterator).getName()+"");
        accNumber.setText(tem.get(iterator).getAccountNumber()+"");
        
    }//GEN-LAST:event_detailsActionPerformed

    private void depositFundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositFundActionPerformed
        try {
            if (amount.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "amount cannot be empty  ");
                return;
            }
            if (Double.parseDouble(amount.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "invalid amount ");
                amount.setText("");
            }
            
            double bal = 0;
            tem=Bank.acc;
            boolean found=false;
            int iterator=0;
            while(true)
            {
                if(tem.get(iterator++).getAccountNumber()==Integer.parseInt(accNumber.getText() ))
                {
                    found=true;
                    break;
                }
                else{
                    
                    if(iterator==tem.size()-1)
                        break;
                }
            }
            if(found)
            {
                bal=tem.get(iterator).getBalance();
            bal += Double.parseDouble(amount.getText());
            balance.setText("" + bal);
            stmt.executeQuery("Update bankaccount set balance='"+bal+"' where accountnumber='"+Integer.parseInt(accNumber.getText())+"'");
            JOptionPane.showMessageDialog(this, "funds deposited successfully  ");
            //DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
//            model.addRow(new Object []{serno++,"deposit ",Double.parseDouble(accNumber.getText()),Double.parseDouble(balance.getText())});
           amount.setText(" ");
                
            }
            
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "amount cannot be empty  execption is ");

        }
    }//GEN-LAST:event_depositFundActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        try {
            BankAccount t = Bank.getAccount(Integer.parseInt(accNumber.getText()));
            if (amount.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "amount cannot be empty  ");
                return;
            }
            if (Double.parseDouble(amount.getText()) > t.balance) {
                JOptionPane.showMessageDialog(this, "Not enough balance try again ");
                amount.setText("");
            }

            double bal = 0;
            tem=Bank.acc;
            int iterator=0;
            boolean found =false;
            while(true)
            {
                if(tem.get(iterator++).getAccountNumber()==Integer.parseInt(accNumber.getText() ))
                    break;
                 if(iterator==tem.size()-1)
                        break;
            }
            if(found)
            {
                bal=tem.get(iterator).getBalance();
            bal-=Integer.parseInt(amount.getText());
            stmt.executeQuery("Update bankaccount set balance='"+bal+"' where accountnumber='"+Integer.parseInt(accNumber.getText())+"'");
//            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
//            model.addRow(new Object []{serno++,"withdraw ",Double.parseDouble(accNumber.getText()),Double.parseDouble(balance.getText())});
            amount.setText(" ");
                
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_withdrawActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        previous.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABE1;
    private javax.swing.JLabel LABE2;
    private javax.swing.JTextField accNumber;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel balance;
    private javax.swing.JButton depositFund;
    private javax.swing.JButton details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton logOut;
    private javax.swing.JButton withdraw;
    // End of variables declaration//GEN-END:variables
}
